name: 'Slack Notifier'
description: 'Envía notificaciones a Slack para pushes y solicitudes de revisión PR'

inputs:
  mode:
    description: 'Tipo de notificación: push o pr-review'
    required: true
  slack_webhook_url:
    description: 'Webhook Slack para notificaciones push'
    required: false
  slack_bot_token:
    description: 'Token Slack Bot para DM en pr-review'
    required: false
  repo_name:
    description: 'Repositorio GitHub (owner/repo)'
    required: true
  branch:
    description: 'Nombre de la rama'
    required: false
  author:
    description: 'Autor del commit o evento'
    required: false
  commit_message:
    description: 'Mensaje del commit'
    required: false
  commit_url:
    description: 'URL al commit en GitHub'
    required: false
  timestamp:
    description: 'Timestamp del evento'
    required: false
  reviewers:
    description: 'Lista de reviewers separados por comas (solo pr-review)'
    required: false
  pr_url:
    description: 'URL de la Pull Request (solo pr-review)'
    required: false

runs:
  using: 'bash'
  main: 'send.sh'
