name: GitKeeper Slack Notifier
description: Send Slack notifications on push or PR assignment

inputs:
  mode:
    description: "Operation mode: 'push' or 'pr-review'"
    required: true
  webhook_url:
    required: false
  slack_bot_token:
    required: false
  repo_name:
    required: false
  branch:
    required: false
  author:
    required: false
  commit_message:
    required: false
  commit_url:
    required: false
  timestamp:
    required: false
  pr_url:
    required: false
  reviewers:
    required: false

runs:
  using: "composite"
  steps:
    - run: bash ${{ github.action_path }}/send.sh
      shell: bash
      env:
        MODE: ${{ inputs.mode }}
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
        REPO: ${{ inputs.repo_name }}
        BRANCH: ${{ inputs.branch }}
        AUTHOR: ${{ inputs.author }}
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
        COMMIT_URL: ${{ inputs.commit_url }}
        TIMESTAMP: ${{ inputs.timestamp }}
        PR_URL: ${{ inputs.pr_url }}
        REVIEWERS: ${{ inputs.reviewers }}
