name: 'Push & PR Review Slack Notification'

description: 'Envía notificaciones por DM vía Slack Bot para pushes y asignación de reviewers'

inputs:
  mode:
    description: 'Modo: push o pr-review'
    required: true
  slack_bot_token:
    description: 'Token del bot de Slack'
    required: true
  push_recipient:
    description: 'Slack ID para notificaciones de push (modo push)'
    required: false
  reviewers:
    description: 'Lista de reviewers (modo pr-review)'
    required: false
  repo_name:
    description: 'Nombre del repositorio'
    required: false
  branch:
    description: 'Nombre de la rama'
    required: false
  author:
    description: 'Autor del commit'
    required: false
  commit_message:
    description: 'Mensaje del commit'
    required: false
  commit_url:
    description: 'URL del commit'
    required: false
  timestamp:
    description: 'Timestamp del commit'
    required: false
  pr_url:
    description: 'URL del pull request (modo pr-review)'
    required: false

runs:
  using: 'bash'
  steps:
    - run: |
        chmod +x $GITHUB_ACTION_PATH/send.sh
        MODE="${{ inputs.mode }}" \
        SLACK_BOT_TOKEN="${{ inputs.slack_bot_token }}" \
        PUSH_RECIPIENT="${{ inputs.push_recipient }}" \
        REVIEWERS="${{ inputs.reviewers }}" \
        REPO_NAME="${{ inputs.repo_name }}" \
        BRANCH="${{ inputs.branch }}" \
        AUTHOR="${{ inputs.author }}" \
        COMMIT_MESSAGE="${{ inputs.commit_message }}" \
        COMMIT_URL="${{ inputs.commit_url }}" \
        TIMESTAMP="${{ inputs.timestamp }}" \
        PR_URL="${{ inputs.pr_url }}" \
        bash $GITHUB_ACTION_PATH/send.sh
