name: GitKeeper – Notify Reviewers via Slack DM

on:
  pull_request:
    types: [review_requested]

jobs:
  notifyReviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Notify assigned reviewers
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          REPO: ${{ github.repository }}
        run: |
          MAP_FILE=".github/slack-reviewer-map.json"

          REVIEWERS=$(echo '${{ toJson(github.event.pull_request.requested_reviewers) }}' | jq -r '.[].login')

          for reviewer in $REVIEWERS; do
            SLACK_ID=$(jq -r --arg user "$reviewer" '.[$user]' "$MAP_FILE")
            if [ "$SLACK_ID" == "null" ] || [ -z "$SLACK_ID" ]; then
              echo "No Slack ID para $reviewer"
              continue
            fi

            curl -X POST https://slack.com/api/chat.postMessage \
              -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
              -H "Content-type: application/json" \
              --data "{
                \"channel\": \"$SLACK_ID\",
                \"text\": \"👋 Te han asignado para revisar un PR en *$REPO*.\n🔗 $PR_URL\"
              }"
          done
