name: GitKeeper – Notify Reviewers via Slack DM (manual map)

on:
  pull_request:
    types: [review_requested]

jobs:
  notifyReviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send DM to assigned reviewers
        uses: ./.github/actions/push-slack-notification
        with:
          mode: pr-review
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          reviewers: ${{ join(github.event.pull_request.requested_reviewers.*.login, ' ') }}
          repo_name: ${{ github.repository }}
          pr_url: ${{ github.event.pull_request.html_url }}
