name: GitKeeper – Daily Pending PR Reminder

on:
  schedule:
    - cron: '15 9 * * *'  # 09:15 UTC → 11:15 en España (CEST)
  workflow_dispatch:

jobs:
  dailyReminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send daily PR reminders
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "📚 Cargando mapa de revisores..."
          MAP_FILE=".github/slack-reviewer-map.json"

          echo "🔍 Buscando PRs abiertas..."
          PRS=$(gh pr list --state open --json number,title,url,createdAt,reviewRequests,reviews,author)

          if [ "$PRS" == "[]" ] || [ -z "$PRS" ]; then
            echo "✅ No hay PRs abiertas para revisar hoy."
            exit 0
          fi

          declare -A reminders

          echo "$PRS" | jq -c '.[]' | while read -r pr; do
            number=$(echo $pr | jq -r '.number')
            title=$(echo $pr | jq -r '.title')
            url=$(echo $pr | jq -r '.url')
            created=$(echo $pr | jq -r '.createdAt')
            reviewers=$(echo $pr | jq -r '.reviewRequests[].login')
            approvals=$(echo $pr | jq -r '.reviews[] | select(.state == "APPROVED") | .author.login' | sort -u)

            # Calcular días desde creación
            created_ts=$(date -d "$created" +%s)
            now_ts=$(date +%s)
            days_open=$(( (now_ts - created_ts) / 86400 ))

            for reviewer in $reviewers; do
              # Ignorar si ya ha aprobado
              if echo "$approvals" | grep -q "^$reviewer$"; then
                continue
              fi

              # Buscar Slack ID
              slack_id=$(jq -r --arg user "$reviewer" '.[$user]' "$MAP_FILE")

              if [ "$slack_id" == "null" ] || [ -z "$slack_id" ]; then
                echo "⚠️ No se encontró Slack ID para $reviewer"
                continue
              fi

              # Agregar mensaje para el revisor
              line="• <$url|#${number}> $title – open for ${days_open} day(s)"
              reminders[$slack_id]="${reminders[$slack_id]}$line\n"
            done
          done

          # Enviar recordatorios
          for slack_id in "${!reminders[@]}"; do
            message="📌 *You have pending PRs to review:*\n${reminders[$slack_id]}"
            echo "📨 Enviando mensaje a $slack_id..."
            curl -s -X POST https://slack.com/api/chat.postMessage \
              -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
              -H "Content-type: application/json" \
              --data "{
                \"channel\": \"$slack_id\",
                \"text\": \"$message\"
              }"
          done
