name: Slack Notification (on push)

on:
  push:
    branches:
      - develop
      - main

jobs:
  slackNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send Slack Notification with curl
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          AUTHOR="${{ github.actor }}"
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          TIMESTAMP="${{ github.event.head_commit.timestamp }}"

          EMOJI=$(jq -r --arg repo "$REPO" '.[$repo] // "📦"' .github/repo-style-map.json)

          curl -X POST -H "Content-type: application/json" --data "$(jq -n \
            --arg emoji "$EMOJI" \
            --arg repo "$REPO" \
            --arg branch "$BRANCH" \
            --arg author "$AUTHOR" \
            --arg message "$COMMIT_MSG" \
            --arg url "$COMMIT_URL" \
            --arg time "$TIMESTAMP" \
            '{
              text: "\($emoji) New push in \($repo)",
              blocks: [
                {
                  type: "header",
                  text: {
                    type: "plain_text",
                    text: "\($emoji) Push in \($repo)",
                    emoji: true
                  }
                },
                {
                  type: "section",
                  fields: [
                    { type: "mrkdwn", text: "*Repositorio:*\n\($repo)" },
                    { type: "mrkdwn", text: "*Rama:*\n\($branch)" },
                    { type: "mrkdwn", text: "*Autor:*\n\($author)" },
                    { type: "mrkdwn", text: "*Commit:*\n\($message)" }
                  ]
                },
                {
                  type: "actions",
                  elements: [
                    {
                      type: "button",
                      text: { type: "plain_text", text: "Ver Commit en GitHub" },
                      url: $url,
                      style: "primary"
                    }
                  ]
                },
                {
                  type: "context",
                  elements: [
                    { type: "mrkdwn", text: "⏰ \($time)" }
                  ]
                }
              ]
            }')" "$SLACK_WEBHOOK_URL"