name: Slack Notification (on push)

on:
  push:
    branches:
      - develop
      - main

jobs:
  slackNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send Slack Notification with curl
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          AUTHOR: ${{ github.actor }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          TIMESTAMP: ${{ github.event.head_commit.timestamp }}
        run: |
          EMOJI=$(jq -r --arg repo "$REPO" '.[$repo] // "📦"' .github/repo-style-map.json)

          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"$EMOJI New push in $REPO\",
            \"blocks\": [
              {
                \"type\": \"header\",
                \"text\": {
                  \"type\": \"plain_text\",
                  \"text\": \"$EMOJI Push in $REPO\",
                  \"emoji\": true
                }
              },
              {
                \"type\": \"section\",
                \"fields\": [
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Repositorio:*\n$REPO\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Rama:*\n$BRANCH\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Autor:*\n$AUTHOR\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Commit:*\n$COMMIT_MSG\"
                  }
                ]
              },
              {
                \"type\": \"actions\",
                \"elements\": [
                  {
                    \"type\": \"button\",
                    \"text\": {
                      \"type\": \"plain_text\",
                      \"text\": \"Ver Commit en GitHub\"
                    },
                    \"url\": \"$COMMIT_URL\",
                    \"style\": \"primary\"
                  }
                ]
              },
              {
                \"type\": \"context\",
                \"elements\": [
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"⏰ $TIMESTAMP\"
                  }
                ]
              }
            ]
          }" "$SLACK_WEBHOOK_URL"
