name: Slack Notification (on push)

on:
  push:
    branches:
      - develop
      - main

jobs:
  slackNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send Slack Notification with curl
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "📦 Cargando estilo de repositorio..."
          STYLE=$(jq -r --arg repo "${{ github.repository }}" '.[$repo]' .github/repo-style-map.json)
          EMOJI=$(echo "$STYLE" | jq -r '.emoji')
          IMAGE_URL=$(echo "$STYLE" | jq -r '.image_url')

          echo "🚀 Enviando notificación a Slack..."
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"${EMOJI} Push in *${{ github.repository }}*\",
            \"blocks\": [
              {
                \"type\": \"image\",
                \"image_url\": \"${IMAGE_URL}\",
                \"alt_text\": \"Repo Logo\"
              },
              {
                \"type\": \"header\",
                \"text\": {
                  \"type\": \"plain_text\",
                  \"text\": \"${EMOJI} Push to ${{ github.ref_name }}\",
                  \"emoji\": true
                }
              },
              {
                \"type\": \"section\",
                \"fields\": [
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Author:*\n${{ github.actor }}\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Commit:*\n${{ github.event.head_commit.message }}\"
                  }
                ]
              },
              {
                \"type\": \"actions\",
                \"elements\": [
                  {
                    \"type\": \"button\",
                    \"text\": {
                      \"type\": \"plain_text\",
                      \"text\": \"🔍 View Commit\"
                    },
                    \"url\": \"${{ github.event.head_commit.url }}\",
                    \"style\": \"primary\"
                  }
                ]
              },
              {
                \"type\": \"context\",
                \"elements\": [
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"⏰ ${{ github.event.head_commit.timestamp }}\"
                  }
                ]
              }
            ]
          }" $SLACK_WEBHOOK_URL
