name: Slack Notification (on push)

on:
  push:
    branches:
      - develop
      - main

jobs:
  slackNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send Slack Notification with curl
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          AUTHOR: ${{ github.actor }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          TIMESTAMP: ${{ github.event.head_commit.timestamp }}
        run: |
          echo "📦 Loading style for $REPO..."
          STYLE=$(jq -r --arg repo "$REPO" '.[$repo]' .github/repo-style-map.json)

          if [ "$STYLE" = "null" ] || [ -z "$STYLE" ]; then
            echo "⚠️ No style found for $REPO, using fallback."
            EMOJI="📦"
            IMAGE_URL="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Git_icon.svg/120px-Git_icon.svg.png"
          else
            EMOJI=$(echo "$STYLE" | jq -r '.emoji')
            IMAGE_URL=$(echo "$STYLE" | jq -r '.image_url')
          fi

          echo "🔔 Sending message with emoji $EMOJI and image $IMAGE_URL..."

          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"${EMOJI} Push in *$REPO*\",
            \"blocks\": [
              {
                \"type\": \"image\",
                \"image_url\": \"$IMAGE_URL\",
                \"alt_text\": \"Repo Logo\"
              },
              {
                \"type\": \"header\",
                \"text\": {
                  \"type\": \"plain_text\",
                  \"text\": \"${EMOJI} Push to $BRANCH\",
                  \"emoji\": true
                }
              },
              {
                \"type\": \"section\",
                \"fields\": [
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Author:*\n$AUTHOR\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Commit:*\n$COMMIT_MESSAGE\"
                  }
                ]
              },
              {
                \"type\": \"actions\",
                \"elements\": [
                  {
                    \"type\": \"button\",
                    \"text\": {
                      \"type\": \"plain_text\",
                      \"text\": \"🔍 View Commit\"
                    },
                    \"url\": \"$COMMIT_URL\",
                    \"style\": \"primary\"
                  }
                ]
              },
              {
                \"type\": \"context\",
                \"elements\": [
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"⏰ $TIMESTAMP\"
                  }
                ]
              }
            ]
          }" $SLACK_WEBHOOK_URL
